In [1]:
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from misc import model_config

In [2]:
main_model_config = (
    model_config.query("main")
    .drop(columns="main")
    .rename(columns={k: f"model_{k}" for k in model_config.columns})
)

new_name = {
    "powermoe": "PowerMoE",
    "llamamoe": "LLaMA-MoE-v1",
    "olmoe": "OLMoE",
    "switch": "SwitchTransformers",
    "llamamoe2": "LLaMA-MoE-v2",
    "jetmoe": "JetMoE",
    "openmoe": "OpenMoE",
    "minicpm": "MiniCPM-MoE",
    "qwen": "Qwen1.5-MoE",
    "deepseek2": "DeepSeek-V2-Lite",
    "deepseek": "DeepSeekMoE",
    "xverse": "XVERSE-MoE",
    "qwen3": "Qwen3",
    "yuan": "Yuan2.0",
    "phi": "Phi-3.5-MoE",
    "grin": "GRIN-MoE",
    "mixtral": "Mixtral-8x7B",
    "jamba": "Jamba-Mini",
    "nllb": "NLLB-MoE",
    "qwen2": "Qwen2",
}

model_colors = {
    key: px.colors.qualitative.Dark24[i] for i, key in enumerate(main_model_config.index.values)
}

seg_lens = (4, 16, 64, 256)
seg_len_colors = {key: px.colors.qualitative.Plotly[i] for i, key in enumerate(seg_lens)}
main_model_config

,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn
key,,,,,,,,
powermoe,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
llamamoe,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager
olmoe,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2
switch,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager
llamamoe2,LLaMA-MoE-v2-3.8B,LL2,causal,8.03,32,8,2,flash_attention_2
jetmoe,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2
openmoe,OpenMoE-8B,OP,causal,11.86,24,32,2,eager
minicpm,MiniCPM-MoE-8x2B,MC,causal,13.87,40,8,2,flash_attention_2
qwen,Qwen1.5-MoE-A2.7B,QW1,causal,14.32,24,60,4,flash_attention_2
deepseek2,DeepSeek-V2-Lite,DS2,causal,15.71,27,64,6,flash_attention_2
deepseek,DeepSeekMoE,DS1,causal,16.38,28,64,6,flash_attention_2
xverse,XVERSE-MoE-A4.2B,XV,causal,25.78,28,64,6,flash_attention_2
qwen3,Qwen3-30B-A3B,QW3,causal,30.53,48,128,8,flash_attention_2
yuan,Yuan2.0-M32,Y2,causal,39.94,24,32,2,flash_attention_2
phi,Phi-3.5-MoE,PH,causal,41.87,32,16,2,flash_attention_2
grin,GRIN-MoE,GR,causal,41.87,32,16,2,flash_attention_2
mixtral,Mixtral-8x7B-v0.1,MX,causal,46.70,32,8,2,flash_attention_2
jamba,Jamba-Mini-1.6,JB,causal,51.57,32,16,2,flash_attention_2
nllb,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager
qwen2,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2

In [3]:
def make_abbr(df):
    return (
        f"{df["model_abbr"]}{"d" if df["is_decoder"] else "e"}"
        if df["model_type"] == "seq2seq"
        else df["model_abbr"]
    )

In [ ]:
root_dir = Path("../output/srp_mpq")

dfs = {
    p.stem: pd.merge(pd.read_parquet(p), main_model_config, left_on="model", right_index=True)
    for p in root_dir.glob("*.parquet")
}

for df in dfs.values():
    df["model"] = df["model"].astype(model_config.index.dtype)

sorted_model_keys = (
    dfs["mg"].query("is_decoder and seg_len == 16").sort_values("best_f1", ascending=False)["model"]
)

dfs["mg"].pivot(index=["model", "is_decoder"], columns="seg_len", values=["best_f1", "best_m"])

                       best_f1                                  best_m  \
seg_len                    4         16        64        256       4
model     is_decoder
powermoe  True        0.670342  0.546897  0.499216  0.478599  1.099400
llamamoe  True        0.558514  0.452756  0.415262  0.405520  1.029958
olmoe     True        0.641371  0.501716  0.446431  0.416328  0.994973
switch    False       0.416009  0.189795  0.119280  0.095175  3.807593
          True        0.417532  0.189005  0.115051       NaN  3.790048
llamamoe2 True        0.839879  0.795945  0.781344  0.773567  1.113026
jetmoe    True        0.603128  0.474550  0.426860  0.410136  1.093049
openmoe   True        0.454657  0.285385  0.214841  0.185045  3.398920
minicpm   True        0.626320  0.489265  0.437200  0.417209  1.107011
qwen      True        0.474554  0.308750  0.224703  0.186311  3.214480
deepseek2 True        0.531624  0.377911  0.304272  0.265834  0.840999
deepseek  True        0.521803  0.367860  0.291856  0.253023  0.826798
xverse    True        0.531407  0.380298  0.305474  0.268357  0.816790
qwen3     True        0.686639  0.559044  0.497820  0.458873  1.005856
yuan      True        0.712601  0.637498  0.615390  0.604062  0.962379
phi       True        0.648108  0.515882  0.461412  0.432992  1.013540
grin      True        0.638514  0.505537  0.451604  0.422865  1.000103
mixtral   True        0.625225  0.492737  0.443179  0.422771  1.113766
jamba     True        0.530526  0.379148  0.309236  0.276487  0.870848
nllb      False       0.442820  0.248391  0.190006  0.161217  3.516512
          True        0.454984  0.309381  0.258170  0.216900  3.395761
qwen2     True        0.506050  0.368641  0.303618  0.274815  0.825725


seg_len                    16        64        256
model     is_decoder
powermoe  True        1.382671  1.616240  1.603849
llamamoe  True        2.389879  2.941798  3.573369
olmoe     True        1.053159  1.198923  1.215971
switch    False       1.944669  2.436540  1.654334
          True        1.961597  2.433251       NaN
llamamoe2 True        1.035956  1.033468  1.042777
jetmoe    True        2.254469  2.696328  3.183836
openmoe   True        1.562222  2.553702  2.348144
minicpm   True        2.181557  2.578542  2.921763
qwen      True        1.841189  2.075404  2.827037
deepseek2 True        1.274911  1.970569  1.978762
deepseek  True        2.283650  1.902990  2.186086
xverse    True        1.226369  1.879043  1.896771
qwen3     True        1.088713  1.127590  1.113615
yuan      True        0.876623  0.911871  0.891849
phi       True        1.141145  1.354241  1.334568
grin      True        1.114436  1.313730  1.326506
mixtral   True        2.175862  2.296733  2.787788
jamba     True        1.454656  2.576524  2.793847
nllb      False       3.292022  1.571335  1.849060
          True        1.386187  1.301518  1.487136
qwen2     True        2.587554  2.461197  2.524852

In [ ]:
vocab_dir = Path("../output/vocab_pq")
vdf = pd.read_parquet(vocab_dir / "gen.parquet")
vdf

,model,layer_idx,expert_idx,token_type,freq,hitoken,hifreq
0,powermoe,0,0,in,0.716081,"[ el, later, il, others, yet, future, on...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
1,powermoe,0,0,out,0.409543,"[;|&, ergency, ;/, hasis, copes, psilon, enuat...","[1.0, 0.990099, 0.98913044, 0.9722222, 0.96774..."
2,powermoe,0,0,pred,0.415233,"[qw, ;|&, ergency, ;/, hasis, psilon, Mgr, enu...","[1.0, 1.0, 0.99029124, 0.9893617, 0.9605263, 0..."
3,powermoe,0,1,in,0.767373,"[ю, wonder, finally, оп, knowledge, diffic...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
4,powermoe,0,1,out,0.381260,"[ (^)(, =====================================...","[1.0, 0.98214287, 0.97727275, 0.9285714, 0.916..."
...,...,...,...,...,...,...,...
71195,qwen2,27,62,out,0.388747,"[ToList, typeof, maxcdn, bitcoin, unfinished, ...","[1.0, 1.0, 1.0, 0.976, 0.9667171, 0.9577465, 0..."
71196,qwen2,27,62,pred,0.391726,"[developer, ToList, stackoverflow, NSDictionar...","[1.0, 1.0, 1.0, 1.0, 0.9677419, 0.96520424, 0...."
71197,qwen2,27,63,in,0.577986,"[ �, hyper, _un, .has, Cos, Kan, "">&, �, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
71198,qwen2,27,63,out,0.416921,"[DOCTYPE, -founder, IMATION, alesce, _UNIQUE, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9815951, 0.97..."
71199,qwen2,27,63,pred,0.430105,"[DOCTYPE, -founder, �, alesce, ibal, -called, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 0.9883721, 0.9803921..."

In [6]:
sample_seg_len = 16
sedf = dfs["eg"].query(f"seg_len == {sample_seg_len}").drop(columns="seg_len")
sedf

,model,is_decoder,layer_idx,expert_idx,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn
1,powermoe,True,0,0,0.586158,0.754772,1.416378,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
5,powermoe,True,0,1,0.503463,0.687003,1.686383,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
9,powermoe,True,0,2,0.323470,0.544055,1.769881,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
13,powermoe,True,0,3,0.370275,0.589426,1.896490,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
17,powermoe,True,0,4,0.366373,0.578746,1.942623,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110573,qwen2,True,27,59,0.124398,0.328928,2.577562,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
110577,qwen2,True,27,60,0.132388,0.335549,2.690522,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
110581,qwen2,True,27,61,0.130088,0.335545,2.668734,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
110585,qwen2,True,27,62,0.133896,0.326095,2.711607,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
110589,qwen2,True,27,63,0.131353,0.332900,2.682075,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2

In [7]:
dedf = pd.merge(
    sedf,
    dfs["ed"]
    .query(f"seg_len == {sample_seg_len} and act_r > 1e-5")
    .drop(columns="seg_len")
    .groupby(["model", "is_decoder", "layer_idx", "expert_idx"], as_index=False, observed=True)
    .apply(
        lambda df: pd.Series({"act_r_cv": df["act_r"].std() / df["act_r"].mean()}),
        include_groups=False,
    ),
)

dedf

,model,is_decoder,layer_idx,expert_idx,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,act_r_cv
0,powermoe,True,0,0,0.586158,0.754772,1.416378,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.168549
1,powermoe,True,0,1,0.503463,0.687003,1.686383,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.138928
2,powermoe,True,0,2,0.323470,0.544055,1.769881,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.291802
3,powermoe,True,0,3,0.370275,0.589426,1.896490,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.145585
4,powermoe,True,0,4,0.366373,0.578746,1.942623,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.150318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23595,qwen2,True,27,59,0.124398,0.328928,2.577562,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.023465
23596,qwen2,True,27,60,0.132388,0.335549,2.690522,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.013797
23597,qwen2,True,27,61,0.130088,0.335545,2.668734,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.022098
23598,qwen2,True,27,62,0.133896,0.326095,2.711607,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.027739
23599,qwen2,True,27,63,0.131353,0.332900,2.682075,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.018028

In [8]:
vedf = pd.merge(
    sedf,
    vdf.pivot(index=["model", "layer_idx", "expert_idx"], columns="token_type", values="freq")
    .rename(columns={k: f"{k}_freq" for k in ("in", "pred", "out")})
    .reset_index(),
)

vedf

,model,is_decoder,layer_idx,expert_idx,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,in_freq,out_freq,pred_freq
0,powermoe,True,0,0,0.586158,0.754772,1.416378,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.716081,0.409543,0.415233
1,powermoe,True,0,1,0.503463,0.687003,1.686383,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.767373,0.381260,0.392808
2,powermoe,True,0,2,0.323470,0.544055,1.769881,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.937067,0.554471,0.525088
3,powermoe,True,0,3,0.370275,0.589426,1.896490,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.957683,0.372158,0.395988
4,powermoe,True,0,4,0.366373,0.578746,1.942623,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.584524,0.321586,0.340565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19825,qwen2,True,27,59,0.124398,0.328928,2.577562,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.568138,0.394762,0.385725
19826,qwen2,True,27,60,0.132388,0.335549,2.690522,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.535303,0.333337,0.348602
19827,qwen2,True,27,61,0.130088,0.335545,2.668734,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.581627,0.326557,0.332072
19828,qwen2,True,27,62,0.133896,0.326095,2.711607,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.533950,0.388747,0.391726
19829,qwen2,True,27,63,0.131353,0.332900,2.682075,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.577986,0.416921,0.430105

In [9]:
smdf = dfs["mg"].query(f"seg_len == {sample_seg_len}").drop(columns="seg_len")
smdf.sort_values("best_f1", ascending=False)

,model,is_decoder,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn
36,llamamoe2,True,0.250000,0.795945,1.035956,LLaMA-MoE-v2-3.8B,LL2,causal,8.03,32,8,2,flash_attention_2
84,yuan,True,0.062500,0.637498,0.876623,Yuan2.0-M32,Y2,causal,39.94,24,32,2,flash_attention_2
80,qwen3,True,0.062500,0.559044,1.088713,Qwen3-30B-A3B,QW3,causal,30.53,48,128,8,flash_attention_2
1,powermoe,True,0.200000,0.546897,1.382671,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
88,phi,True,0.125000,0.515882,1.141145,Phi-3.5-MoE,PH,causal,41.87,32,16,2,flash_attention_2
92,grin,True,0.125000,0.505537,1.114436,GRIN-MoE,GR,causal,41.87,32,16,2,flash_attention_2
13,olmoe,True,0.125000,0.501716,1.053159,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2
96,mixtral,True,0.250000,0.492737,2.175862,Mixtral-8x7B-v0.1,MX,causal,46.70,32,8,2,flash_attention_2
60,minicpm,True,0.250000,0.489265,2.181557,MiniCPM-MoE-8x2B,MC,causal,13.87,40,8,2,flash_attention_2
44,jetmoe,True,0.250000,0.474550,2.254469,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2
5,llamamoe,True,0.250000,0.452756,2.389879,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager
76,xverse,True,0.093750,0.380298,1.226369,XVERSE-MoE-A4.2B,XV,causal,25.78,28,64,6,flash_attention_2
100,jamba,True,0.125000,0.379148,1.454656,Jamba-Mini-1.6,JB,causal,51.57,32,16,2,flash_attention_2
68,deepseek2,True,0.093750,0.377911,1.274911,DeepSeek-V2-Lite,DS2,causal,15.71,27,64,6,flash_attention_2
112,qwen2,True,0.125000,0.368641,2.587554,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
72,deepseek,True,0.093750,0.367860,2.283650,DeepSeekMoE,DS1,causal,16.38,28,64,6,flash_attention_2
108,nllb,True,0.015625,0.309381,1.386187,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager
64,qwen,True,0.066667,0.308750,1.841189,Qwen1.5-MoE-A2.7B,QW1,causal,14.32,24,60,4,flash_attention_2
56,openmoe,True,0.062500,0.285385,1.562222,OpenMoE-8B,OP,causal,11.86,24,32,2,eager
104,nllb,False,0.015625,0.248391,3.292022,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager
29,switch,False,0.007812,0.189795,1.944669,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager
33,switch,True,0.007812,0.189005,1.961597,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager

In [10]:
dmcdf = pd.merge(
    smdf,
    dedf.groupby(["model", "is_decoder"], as_index=False, observed=True).apply(
        lambda df: pd.Series(
            {"ds": df["act_r_cv"].mean(), "corr": df["best_f1"].corr(df["act_r_cv"])}
        ),
        include_groups=False,
    ),
)

dmcdf.sort_values("best_f1", ascending=False)

,model,is_decoder,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,ds,corr
5,llamamoe2,True,0.250000,0.795945,1.035956,LLaMA-MoE-v2-3.8B,LL2,causal,8.03,32,8,2,flash_attention_2,0.719625,-0.384651
14,yuan,True,0.062500,0.637498,0.876623,Yuan2.0-M32,Y2,causal,39.94,24,32,2,flash_attention_2,0.782017,0.135393
13,qwen3,True,0.062500,0.559044,1.088713,Qwen3-30B-A3B,QW3,causal,30.53,48,128,8,flash_attention_2,0.961794,0.610651
0,powermoe,True,0.200000,0.546897,1.382671,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.360711,0.092346
15,phi,True,0.125000,0.515882,1.141145,Phi-3.5-MoE,PH,causal,41.87,32,16,2,flash_attention_2,0.684874,0.835672
16,grin,True,0.125000,0.505537,1.114436,GRIN-MoE,GR,causal,41.87,32,16,2,flash_attention_2,0.664727,0.852600
2,olmoe,True,0.125000,0.501716,1.053159,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2,0.570060,0.784188
17,mixtral,True,0.250000,0.492737,2.175862,Mixtral-8x7B-v0.1,MX,causal,46.70,32,8,2,flash_attention_2,0.068396,0.119815
8,minicpm,True,0.250000,0.489265,2.181557,MiniCPM-MoE-8x2B,MC,causal,13.87,40,8,2,flash_attention_2,0.085586,0.202361
6,jetmoe,True,0.250000,0.474550,2.254469,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2,0.068118,0.563107
1,llamamoe,True,0.250000,0.452756,2.389879,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,0.030156,-0.347601
12,xverse,True,0.093750,0.380298,1.226369,XVERSE-MoE-A4.2B,XV,causal,25.78,28,64,6,flash_attention_2,0.246749,0.698996
18,jamba,True,0.125000,0.379148,1.454656,Jamba-Mini-1.6,JB,causal,51.57,32,16,2,flash_attention_2,0.154271,0.188941
10,deepseek2,True,0.093750,0.377911,1.274911,DeepSeek-V2-Lite,DS2,causal,15.71,27,64,6,flash_attention_2,0.246980,0.731287
21,qwen2,True,0.125000,0.368641,2.587554,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.040516,-0.591047
11,deepseek,True,0.093750,0.367860,2.283650,DeepSeekMoE,DS1,causal,16.38,28,64,6,flash_attention_2,0.211088,0.709563
20,nllb,True,0.015625,0.309381,1.386187,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager,0.580198,0.301820
9,qwen,True,0.066667,0.308750,1.841189,Qwen1.5-MoE-A2.7B,QW1,causal,14.32,24,60,4,flash_attention_2,0.152100,0.571489
7,openmoe,True,0.062500,0.285385,1.562222,OpenMoE-8B,OP,causal,11.86,24,32,2,eager,0.113624,0.166333
19,nllb,False,0.015625,0.248391,3.292022,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager,0.423167,0.087459
3,switch,False,0.007812,0.189795,1.944669,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager,0.509999,0.328902
4,switch,True,0.007812,0.189005,1.961597,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager,0.532878,0.280602

In [11]:
vmcdf = pd.merge(
    smdf,
    vedf.groupby(["model", "is_decoder"], as_index=False, observed=True).apply(
        lambda df: pd.concat(
            [
                pd.Series(
                    {
                        f"{k}_vs": df[f"{k}_freq"].mean(),
                        f"{k}_corr": df["best_f1"].corr(df[f"{k}_freq"]),
                    }
                )
                for k in ("in", "pred", "out")
            ]
        ),
        include_groups=False,
    ),
)

vmcdf.sort_values("best_f1", ascending=False)

,model,is_decoder,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,in_vs,in_corr,pred_vs,pred_corr,out_vs,out_corr
3,llamamoe2,True,0.250000,0.795945,1.035956,LLaMA-MoE-v2-3.8B,LL2,causal,8.03,32,8,2,flash_attention_2,0.598470,0.403954,0.548307,0.377976,0.510857,0.522829
12,yuan,True,0.062500,0.637498,0.876623,Yuan2.0-M32,Y2,causal,39.94,24,32,2,flash_attention_2,0.691903,-0.013227,0.542319,0.355939,0.521721,0.349479
11,qwen3,True,0.062500,0.559044,1.088713,Qwen3-30B-A3B,QW3,causal,30.53,48,128,8,flash_attention_2,0.358386,-0.109257,0.296604,0.072896,0.270623,0.066577
0,powermoe,True,0.200000,0.546897,1.382671,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.483509,-0.174071,0.365946,-0.119466,0.342915,-0.169185
13,phi,True,0.125000,0.515882,1.141145,Phi-3.5-MoE,PH,causal,41.87,32,16,2,flash_attention_2,0.612866,-0.295235,0.479991,0.334127,0.451882,0.322514
14,grin,True,0.125000,0.505537,1.114436,GRIN-MoE,GR,causal,41.87,32,16,2,flash_attention_2,0.611601,-0.298569,0.477520,0.334495,0.450676,0.322358
2,olmoe,True,0.125000,0.501716,1.053159,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2,0.408042,0.163676,0.312994,0.426681,0.277581,0.416215
15,mixtral,True,0.250000,0.492737,2.175862,Mixtral-8x7B-v0.1,MX,causal,46.70,32,8,2,flash_attention_2,0.550430,-0.219873,0.419642,-0.160210,0.398677,-0.179002
6,minicpm,True,0.250000,0.489265,2.181557,MiniCPM-MoE-8x2B,MC,causal,13.87,40,8,2,flash_attention_2,0.578196,-0.182592,0.437184,0.213791,0.408081,0.216529
4,jetmoe,True,0.250000,0.474550,2.254469,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2,0.664980,-0.603605,0.470143,0.225515,0.442950,0.204228
1,llamamoe,True,0.250000,0.452756,2.389879,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,0.543617,0.179556,0.378709,0.082688,0.350340,0.094764
10,xverse,True,0.093750,0.380298,1.226369,XVERSE-MoE-A4.2B,XV,causal,25.78,28,64,6,flash_attention_2,0.417506,-0.562669,0.259793,-0.222572,0.245950,-0.271622
16,jamba,True,0.125000,0.379148,1.454656,Jamba-Mini-1.6,JB,causal,51.57,32,16,2,flash_attention_2,0.508194,0.089684,0.372150,0.180461,0.351456,0.193585
8,deepseek2,True,0.093750,0.377911,1.274911,DeepSeek-V2-Lite,DS2,causal,15.71,27,64,6,flash_attention_2,0.437156,-0.084477,0.347816,0.135140,0.316438,0.089617
17,qwen2,True,0.125000,0.368641,2.587554,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.421570,-0.283892,0.265251,-0.154368,0.245470,-0.173733
9,deepseek,True,0.093750,0.367860,2.283650,DeepSeekMoE,DS1,causal,16.38,28,64,6,flash_attention_2,0.453927,-0.203285,0.346177,0.101748,0.312817,0.059655
7,qwen,True,0.066667,0.308750,1.841189,Qwen1.5-MoE-A2.7B,QW1,causal,14.32,24,60,4,flash_attention_2,0.497326,-0.097366,0.333751,0.253869,0.302605,0.237788
5,openmoe,True,0.062500,0.285385,1.562222,OpenMoE-8B,OP,causal,11.86,24,32,2,eager,0.789977,-0.398419,0.314766,0.173956,0.278716,0.030922

In [ ]:
fig = make_subplots(
    rows=1,
    cols=len(seg_lens),
    shared_xaxes="all",
    horizontal_spacing=0.01,
    subplot_titles=[
        "Domain Specialization",
        "Input Vocabulary Specialization",
        "Pred. Output Vocab. Spec.",
        "G. T. Output Vocab. Spec.",
    ],
)

text_pos = [
    {
        "powermoe": "bottom center",
        "llamamoe": "bottom center",
        "olmoe": "bottom center",
        "switch": ["top center", "bottom center"],
        "llamamoe2": "bottom center",
        "jetmoe": "bottom center",
        "openmoe": "middle right",
        "minicpm": "middle left",
        "qwen": "bottom center",
        "deepseek2": "top center",
        "deepseek": "middle left",
        "xverse": "middle right",
        "qwen3": "bottom center",
        "yuan": "bottom center",
        "phi": "middle right",
        "grin": "middle left",
        "mixtral": "middle left",
        "jamba": "bottom center",
        "nllb": ["bottom center", "middle right"],
        "qwen2": "bottom center",
    },
    {
        "powermoe": "middle right",
        "llamamoe": "bottom center",
        "olmoe": "bottom center",
        "llamamoe2": "bottom center",
        "jetmoe": "bottom center",
        "openmoe": "bottom center",
        "minicpm": "top center",
        "qwen": "bottom center",
        "deepseek2": "middle right",
        "deepseek": "middle right",
        "xverse": "bottom center",
        "qwen3": "top center",
        "yuan": "bottom center",
        "phi": "middle right",
        "grin": "middle left",
        "mixtral": "middle left",
        "jamba": "bottom center",
        "qwen2": "bottom center",
    },
    {
        "powermoe": "bottom center",
        "llamamoe": "bottom center",
        "olmoe": "top center",
        "llamamoe2": "bottom center",
        "jetmoe": "middle left",
        "openmoe": "bottom center",
        "minicpm": "bottom center",
        "qwen": "top center",
        "deepseek2": "middle right",
        "deepseek": "bottom center",
        "xverse": "bottom center",
        "qwen3": "bottom center",
        "yuan": "bottom center",
        "phi": "middle right",
        "grin": "middle left",
        "mixtral": "bottom center",
        "jamba": "top center",
        "qwen2": "top center",
    },
    {
        "powermoe": "bottom center",
        "llamamoe": "bottom center",
        "olmoe": "top center",
        "llamamoe2": "bottom center",
        "jetmoe": "bottom center",
        "openmoe": "bottom center",
        "minicpm": "middle right",
        "qwen": "top center",
        "deepseek2": "middle right",
        "deepseek": "bottom center",
        "xverse": "bottom center",
        "qwen3": "bottom center",
        "yuan": "bottom center",
        "phi": "middle right",
        "grin": "middle left",
        "mixtral": "bottom center",
        "jamba": "top center",
        "qwen2": "top center",
    },
]

font_size = [16, 20, 24, 28]

for j, key in enumerate(main_model_config.index.values):
    tmpdf = dmcdf.query(f"model == '{key}'")
    if len(tmpdf) == 0:
        continue

    fig.add_scatter(
        x=tmpdf["best_f1"],
        y=tmpdf["corr"],
        hoverinfo="skip",
        marker=go.scatter.Marker(
            color=model_colors[key],
            line=go.scatter.marker.Line(color="white", width=1),
            opacity=0.7,
            size=tmpdf["ds"] ** 0.5 * 30,
        ),
        legendgroup=key,
        mode="markers+text",
        name=new_name[key],
        showlegend=True,
        text=tmpdf.apply(make_abbr, axis=1),
        textfont=go.scatter.Textfont(size=font_size[0], shadow="auto"),
        textposition=text_pos[0][key],
        zorder=100 - j,
        row=1,
        col=1,
    )

    fig.update_xaxes(
        tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
        title=go.layout.xaxis.Title(
            font=go.layout.xaxis.title.Font(size=font_size[2]), text=f"SRP(E,{sample_seg_len})"
        ),
        row=1,
        col=1,
    )

    fig.update_yaxes(
        range=[-1, 1],
        showticklabels=True,
        tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
        title=go.layout.yaxis.Title(
            font=go.layout.yaxis.title.Font(size=font_size[2]),
            text="Correlation",
        ),
        row=1,
        col=1,
    )

for j, key in enumerate(main_model_config.index.values):
    tmpdf = vmcdf.query(f"model == '{key}'")
    if len(tmpdf) == 0:
        continue

    for i, prefix in enumerate(("in", "pred", "out")):
        col = i + 2

        fig.add_scatter(
            x=tmpdf["best_f1"],
            y=tmpdf[f"{prefix}_corr"],
            hoverinfo="skip",
            marker=go.scatter.Marker(
                color=model_colors[key],
                line=go.scatter.marker.Line(color="white", width=1),
                opacity=0.7,
                size=tmpdf[f"{prefix}_vs"] * 30,
            ),
            legendgroup=key,
            mode="markers+text",
            name=new_name[key],
            showlegend=False,
            text=tmpdf.apply(make_abbr, axis=1),
            textfont=go.scatter.Textfont(size=font_size[0], shadow="auto"),
            textposition=text_pos[i + 1][key],
            zorder=100 - j,
            row=1,
            col=col,
        )

        fig.update_xaxes(
            tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
            title=go.layout.xaxis.Title(
                font=go.layout.xaxis.title.Font(size=font_size[2]), text=f"SRP(E,{sample_seg_len})"
            ),
            row=1,
            col=col,
        )

        fig.update_yaxes(range=[-1, 1], showticklabels=False, row=1, col=col)

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))

fig.update_layout(
    legend=go.layout.Legend(
        font=go.layout.legend.Font(size=font_size[1]),
        itemsizing="constant",
        orientation="h",
        y=-0.15,
        yanchor="top",
    ),
    margin=go.layout.Margin(l=60, r=30, t=30, b=0),
    width=2000,
    height=600,
)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "msrpsc.pdf")
# fig.show()

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.02,
    vertical_spacing=0.08,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [14, 16, 18, 20]

for i, key in enumerate(sorted_model_keys):
    if (dedf["model"] == key).sum() == 0:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    tmpdf = dedf.query(f"model == '{key}'")
    num_layers = model_config.loc[key, "num_layers"]
    layer_idx = tmpdf["layer_idx"] + 1

    if model_config.loc[key, "type"] == "seq2seq":
        layer_idx += tmpdf["is_decoder"] * num_layers // 2

    fig.add_scatter(
        x=tmpdf["act_r_cv"],
        y=tmpdf["best_f1"],
        hoverinfo="skip",
        marker=go.scatter.Marker(
            cmax=num_layers,
            cmin=1,
            color=layer_idx + 1,
            colorbar=go.scatter.marker.ColorBar(
                len=0.49,
                thickness=10,
                x=(col - 0.23) * 0.102,
                y=(num_rows - 1 - row + 1.45) * 0.54,
                tickfont=go.scatter.marker.colorbar.Tickfont(size=font_size[0]),
                tickvals=[1, num_layers // 2, num_layers],
                title=go.scatter.marker.colorbar.Title(
                    font=go.scatter.marker.colorbar.title.Font(size=font_size[1]), text="Ly."
                ),
            ),
            size=5,
        ),
        mode="markers",
        showlegend=False,
        row=row,
        col=col,
    )

    fig.update_xaxes(showticklabels=row == num_rows, row=row, col=col)

    if row == num_rows:
        fig.update_xaxes(
            title=go.layout.xaxis.Title(
                font=go.layout.xaxis.title.Font(size=font_size[2]), standoff=5, text="Domain Spec."
            ),
            tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

    if col == 1:
        fig.update_yaxes(
            showticklabels=True,
            title=go.layout.yaxis.Title(
                font=go.layout.yaxis.title.Font(size=font_size[2]), text=f"SRP(e,{sample_seg_len})"
            ),
            tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=60, r=0, t=30, b=0), width=2000, height=500)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "esrpds.pdf")
# fig.show()

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.02,
    vertical_spacing=0.08,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [14, 16, 18, 20]

for i, key in enumerate(sorted_model_keys):
    if (vedf["model"] == key).sum() == 0:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    tmpdf = vedf.query(f"model == '{key}'")
    num_layers = model_config.loc[key, "num_layers"]
    layer_idx = tmpdf["layer_idx"] + 1

    if model_config.loc[key, "type"] == "seq2seq":
        layer_idx += tmpdf["is_decoder"] * num_layers // 2

    fig.add_scatter(
        x=tmpdf["in_freq"],
        y=tmpdf["best_f1"],
        hoverinfo="skip",
        marker=go.scatter.Marker(
            cmax=num_layers,
            cmin=1,
            color=layer_idx + 1,
            colorbar=go.scatter.marker.ColorBar(
                len=0.49,
                thickness=10,
                x=(col - 0.23) * 0.102,
                y=(num_rows - 1 - row + 1.45) * 0.54,
                tickfont=go.scatter.marker.colorbar.Tickfont(size=font_size[0]),
                tickvals=[1, num_layers // 2, num_layers],
                title=go.scatter.marker.colorbar.Title(
                    font=go.scatter.marker.colorbar.title.Font(size=font_size[1]), text="Ly."
                ),
            ),
            size=5,
        ),
        mode="markers",
        showlegend=False,
        row=row,
        col=col,
    )

    fig.update_xaxes(showticklabels=row == num_rows, row=row, col=col)

    if row == num_rows:
        fig.update_xaxes(
            title=go.layout.xaxis.Title(
                font=go.layout.xaxis.title.Font(size=font_size[2]),
                standoff=5,
                text="In. Vocab. Spec.",
            ),
            tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

    if col == 1:
        fig.update_yaxes(
            showticklabels=True,
            title=go.layout.yaxis.Title(
                font=go.layout.yaxis.title.Font(size=font_size[2]), text=f"SRP(e,{sample_seg_len})"
            ),
            tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=60, r=0, t=30, b=0), width=2000, height=500)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "esrpivs.pdf")
# fig.show()

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.02,
    vertical_spacing=0.08,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [14, 16, 18, 20]

for i, key in enumerate(sorted_model_keys):
    if (vedf["model"] == key).sum() == 0:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    tmpdf = vedf.query(f"model == '{key}'")
    num_layers = model_config.loc[key, "num_layers"]
    layer_idx = tmpdf["layer_idx"] + 1

    if model_config.loc[key, "type"] == "seq2seq":
        layer_idx += tmpdf["is_decoder"] * num_layers // 2

    fig.add_scatter(
        x=tmpdf["pred_freq"],
        y=tmpdf["best_f1"],
        hoverinfo="skip",
        marker=go.scatter.Marker(
            cmax=num_layers,
            cmin=1,
            color=layer_idx + 1,
            colorbar=go.scatter.marker.ColorBar(
                len=0.49,
                thickness=10,
                x=(col - 0.23) * 0.102,
                y=(num_rows - 1 - row + 1.45) * 0.54,
                tickfont=go.scatter.marker.colorbar.Tickfont(size=font_size[0]),
                tickvals=[1, num_layers // 2, num_layers],
                title=go.scatter.marker.colorbar.Title(
                    font=go.scatter.marker.colorbar.title.Font(size=font_size[1]), text="Ly."
                ),
            ),
            size=5,
        ),
        mode="markers",
        showlegend=False,
        row=row,
        col=col,
    )

    fig.update_xaxes(showticklabels=row == num_rows, row=row, col=col)

    if row == num_rows:
        fig.update_xaxes(
            title=go.layout.xaxis.Title(
                font=go.layout.xaxis.title.Font(size=font_size[2]),
                standoff=5,
                text="G. T. O. Vocab. Spec.",
            ),
            tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

    if col == 1:
        fig.update_yaxes(
            showticklabels=True,
            title=go.layout.yaxis.Title(
                font=go.layout.yaxis.title.Font(size=font_size[2]), text=f"SRP(e,{sample_seg_len})"
            ),
            tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=60, r=0, t=30, b=0), width=2000, height=500)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "esrpovs.pdf")
# fig.show()

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.02,
    vertical_spacing=0.08,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [14, 16, 18, 20]

for i, key in enumerate(sorted_model_keys):
    if (vedf["model"] == key).sum() == 0:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    tmpdf = vedf.query(f"model == '{key}'")
    num_layers = model_config.loc[key, "num_layers"]
    layer_idx = tmpdf["layer_idx"] + 1

    if model_config.loc[key, "type"] == "seq2seq":
        layer_idx += tmpdf["is_decoder"] * num_layers // 2

    fig.add_scatter(
        x=tmpdf["pred_freq"],
        y=tmpdf["best_f1"],
        hoverinfo="skip",
        marker=go.scatter.Marker(
            cmax=num_layers,
            cmin=1,
            color=layer_idx + 1,
            colorbar=go.scatter.marker.ColorBar(
                len=0.49,
                thickness=10,
                x=(col - 0.23) * 0.102,
                y=(num_rows - 1 - row + 1.45) * 0.54,
                tickfont=go.scatter.marker.colorbar.Tickfont(size=font_size[0]),
                tickvals=[1, num_layers // 2, num_layers],
                title=go.scatter.marker.colorbar.Title(
                    font=go.scatter.marker.colorbar.title.Font(size=font_size[1]), text="Ly."
                ),
            ),
            size=5,
        ),
        mode="markers",
        showlegend=False,
        row=row,
        col=col,
    )

    fig.update_xaxes(showticklabels=row == num_rows, row=row, col=col)

    if row == num_rows:
        fig.update_xaxes(
            title=go.layout.xaxis.Title(
                font=go.layout.xaxis.title.Font(size=font_size[2]),
                standoff=5,
                text="P. O. Vocab. Spec.",
            ),
            tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

    if col == 1:
        fig.update_yaxes(
            showticklabels=True,
            title=go.layout.yaxis.Title(
                font=go.layout.yaxis.title.Font(size=font_size[2]), text=f"SRP(e,{sample_seg_len})"
            ),
            tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
            row=row,
            col=col,
        )

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=60, r=0, t=30, b=0), width=2000, height=500)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "esrppvs.pdf")
# fig.show()

In [17]:
gedf = (
    pd.merge(
        dedf.groupby(["model", "is_decoder"], observed=True)
        .apply(
            lambda df: df.query("act_r < 0.8").sort_values("best_f1", ascending=False).head(1),
            include_groups=False,
        )
        .reset_index(["model", "is_decoder"])
        .reset_index(drop=True),
        vdf,
    )
    .drop(columns="is_decoder")
    .explode(["hitoken", "hifreq"])
)

gedf

,model,layer_idx,expert_idx,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,act_r_cv,token_type,freq,hitoken,hifreq
0,powermoe,22,39,0.410648,0.870613,1.086282,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.872655,in,0.426903,Creates,1.0
0,powermoe,22,39,0.410648,0.870613,1.086282,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.872655,in,0.426903,Computes,1.0
0,powermoe,22,39,0.410648,0.870613,1.086282,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.872655,in,0.426903,compute,0.984615
0,powermoe,22,39,0.410648,0.870613,1.086282,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.872655,in,0.426903,Assume,0.964286
0,powermoe,22,39,0.410648,0.870613,1.086282,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,0.872655,in,0.426903,truncated,0.960784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,qwen2,1,38,0.639861,0.781630,1.520221,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.003664,pred,0.137710,hospitality,0.227273
53,qwen2,1,38,0.639861,0.781630,1.520221,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.003664,pred,0.137710,bian,0.227273
53,qwen2,1,38,0.639861,0.781630,1.520221,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.003664,pred,0.137710,gements,0.222222
53,qwen2,1,38,0.639861,0.781630,1.520221,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.003664,pred,0.137710,Ottawa,0.217391
53,qwen2,1,38,0.639861,0.781630,1.520221,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,0.003664,pred,0.137710,-effective,0.217391